### ISSUE TITLE
remove bs4 from bs triggers

### ISSUE THREAD

**Issue by hulleyrob** [futureprogrammer360/Python-Web-Scraping-Snippets#1]
if the "ibs" trigger is "from bs4 import BeautifulSoup" then why do all the "bs" triggers include the "bs4" part?

otherwise I can see this being quite useful.

**Comment by futureprogrammer360** [comment]
Hello there, I'm not quite sure what you mean, could you please clarify?
The beautifulsoup4 snippets don't have `bs4` as part of the triggers, are you referring to the `description`s instead?

**Comment by hulleyrob** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/17217514/230737657-7f316fba-bb51-49e3-8f41-c47402f67be4.png">

I was referring to the above.

EDIT: just got round to trying it, and I see that the actual snippets don't have it. I was just reading the above and thought they would have.

**Comment by futureprogrammer360** [comment]
Ah, I see now. Yeah, these are just descriptions of the snippets, not the actual triggers.
Closing the issue if you don't have any further concerns. Thanks for reaching out!

**Comment by hulleyrob** [comment]
Yep all good.
